Repository eclipse-tractusx/industry-core-hub, pull requests merged in 2025-05, with the labels that each got.

#199 fix: correct indentation and import errors
  ichub-backend/models/metadata_database/models.py
  ichub-backend/runtimes/fastapi/main.py
Labels: bug

#198 feat: bump dependency versions for improved security and compatibility
  .github/workflows/dependencies-backend.yml
  DEPENDENCIES_ICHUB-BACKEND
  ichub-backend/requirements.txt
Labels: dependencies

#206 chore: Update helm-test.yaml to include upgrade step (TRG 5.11)
  .github/workflows/helm-test.yaml
Labels: infrastructure

#220 docs(TRG 1.02): Add installation guide for Industry Core Hub
  INSTALL.md
  README.md
Labels: documentation
